//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearningManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonId { get; set; }
        public int CourseId { get; set; }
        public string LessonTitle { get; set; }
        public string Content { get; set; }
        public string VideoUrl { get; set; }
        public int SequenceOrder { get; set; }
        public Nullable<bool> IsCheckpoint { get; set; }
        public string PdfUrl { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
